/* How Big? object catalog.
   RAW rows: [id, emoji (null = drawn art), prompt, height in meters, note, label].
   STD rows: [id, picture, prompt, height in feet, note, label, theme, familiarity (1-10)].
   Keep these values and IDs stable; game logic combines both row types into the live catalog. */
window.HOW_BIG_OBJECTS = (() => {
  const FT = 0.3048;
  return {
    RAW: [
  ['battery','🔋','an AA battery',0.0505,'',''],
  ['baseball','⚾','a baseball',0.074,'',''],
  ['softball','🥎','a softball',0.097,'',''],
  ['phone','📱','a smartphone',0.147,'standing upright',''],
  ['soccer','⚽','a soccer ball',0.22,'',''],
  ['basketball','🏀','a basketball',0.24,'',''],
  ['trophy','🏆','the FIFA World Cup trophy',0.368,'','World Cup trophy'],
  ['bucket','🪣','a 5-gallon bucket',0.37,'','Bucket'],
  ['toilet','🚽','a toilet',0.76,'',''],
  ['chair','🪑','a dining chair',0.9,'',''],
  ['tiger','🐅','a Bengal tiger',1.30,'standing, ground to the top of its ears','Tiger'],
  ['penguin','🐧','an emperor penguin',1.0,'standing','Emperor penguin'],
  ['bike','🚲','a bicycle',1.0,'',''],
  ['flamingo','🦩','a flamingo',1.3,'',''],
  ['hippo','🦛','a hippo',1.55,'standing, ground to the top of its ears',''],
  ['car','🚗','a compact car',1.44,'',''],
  ['cow','🐄','a Holstein cow',1.68,'standing, ground to the top of its head and horns','Cow'],
  ['horse','🐎','a horse',2.06,'standing, ground to the top of its ears',''],
  ['person','🧍','an adult person',1.7,'',''],
  ['rhino','🦏','a white rhino',1.98,'standing, ground to the top of its horn',''],
  ['bison','🦬','an American bison',1.92,'standing, ground to the top of its horns','Bison'],
  ['pickup','🛻','a full-size pickup truck',1.96,'','Pickup truck'],
  ['door','🚪','a door',2.03,'',''],
  ['camel','🐪','a camel',2.29,'standing, ground to the top of its ears',''],
  ['xmastree','🎄','a 7.5-foot Christmas tree',2.29,'','Christmas tree'],
  ['goal','🥅','a soccer goal',2.44,'',''],
  ['mammoth','🦣','a woolly mammoth',3.66,'standing, ground to the top of its head',''],
  ['elephant','🐘','an African elephant',3.66,'adult bull, ground to the top of its head and ears','Elephant'],
  ['bus','🚌','a city bus',3.2,'',''],
  ['giraffe','🦒','a male giraffe',5.49,'standing, ground to the top of its ossicones','Giraffe'],
  ['stonehenge',null,'the tallest stone at Stonehenge',6.7,'above ground','Stonehenge'],
  ['brachio','🦕','a Brachiosaurus',12,'with its head raised',''],
  ['hollywood',null,'the Hollywood sign',13.4,'letter height','Hollywood sign'],
  ['sphinx',null,'the Great Sphinx of Giza',20,'','Great Sphinx'],
  ['christ',null,'Christ the Redeemer',38,'including its pedestal','Christ the Redeemer'],
  ['liberty','🗽','the Statue of Liberty',46,'heel to torch, without the pedestal','Statue of Liberty'],
  ['colosseum',null,'the Colosseum',48,'outer wall','Colosseum'],
  ['pisa',null,'the Leaning Tower of Pisa',61.6,'ground to the top of the flag on its high side (approximate)','Tower of Pisa'],
  ['opera',null,'the Sydney Opera House',67,'highest roof, above sea level','Sydney Opera House'],
  ['taj',null,'the Taj Mahal',73,'','Taj Mahal'],
  ['bigben',null,'Big Ben',96,'the Elizabeth Tower','Big Ben'],
  ['saturnv',null,'a Saturn V rocket',111,'','Saturn V rocket'],
  ['hyperion','🌲','Hyperion, the world\'s tallest tree',116,'a coast redwood','Hyperion (redwood)'],
  ['londoneye','🎡','the London Eye',135,'','London Eye'],
  ['pyramid',null,'the Great Pyramid of Giza',138.5,'as it stands today','Great Pyramid'],
  ['washington',null,'the Washington Monument',169,'','Washington Monument'],
  ['spaceneedle',null,'the Space Needle',184,'','Space Needle'],
  ['arch',null,'the Gateway Arch',192,'','Gateway Arch'],
  ['goldengate',null,'a Golden Gate Bridge tower',227,'above the water','Golden Gate tower'],
  ['eiffel',null,'the Eiffel Tower',330,'','Eiffel Tower'],
  ['empire',null,'the Empire State Building',443,'ground to the top of its antenna','Empire State Building'],
  ['onewtc',null,'One World Trade Center',541,'','One World Trade Center'],
  ['cntower',null,'the CN Tower',553,'','CN Tower'],
  ['skytree',null,'Tokyo Skytree',634,'','Tokyo Skytree'],
  ['burj',null,'the Burj Khalifa',828,'','Burj Khalifa'],
  ['fuji','🗻','Mount Fuji',3776,'above sea level','Mount Fuji'],
  ['everest','🏔️','Mount Everest',8849,'above sea level','Mount Everest'],
  ['dangi',null,'Chandra Bahadur Dangi, the shortest adult on record',0.61,'standing, ground to the top of his hat','Chandra Bahadur Dangi'],
  ['biles',null,'Simone Biles',1.65,'in the pictured pose, ground to the top of her raised fingers','Simone Biles'],
  ['bogues',null,'Muggsy Bogues',1.6,'listed height','Muggsy Bogues'],
  ['messi',null,'Lionel Messi',1.7,'listed height','Lionel Messi'],
  ['clark',null,'Caitlin Clark',1.83,'listed height','Caitlin Clark'],
  ['curry',null,'Stephen Curry',1.88,'listed height','Stephen Curry'],
  ['bolt',null,'Usain Bolt',1.95,'listed height','Usain Bolt'],
  ['lebron',null,'LeBron James',2.06,'listed height','LeBron James'],
  ['shaq',null,"Shaquille O'Neal",2.16,'listed height',"Shaquille O'Neal"],
  ['wemby',null,'Victor Wembanyama',2.24,'listed height','Victor Wembanyama'],
  ['yao',null,'Yao Ming',2.29,'listed height','Yao Ming'],
  ['zeng',null,'Zeng Jinlian, the tallest woman on record',2.463,'Guinness World Record','Zeng Jinlian'],
  ['wadlow',null,'Robert Wadlow, the tallest person on record',2.72,'Guinness World Record','Robert Wadlow'],
  ['a380',null,'an Airbus A380 jet',24,'to the top of the tail','Airbus A380'],
  ['titanic',null,'the Titanic',53.3,'keel to the top of the funnels','Titanic'],
  ['shuttle',null,'a Space Shuttle on the launch pad',56,'full launch stack','Space Shuttle'],
  ],
    RAW2: [
  ['die','🎲','a six-sided die',0.016,'standard size','Die'],
  ['pingpong',null,'a ping-pong ball',0.04,'',''],
  ['golfball',null,'a golf ball',0.0427,'',''],
  ['tennisball',null,'a tennis ball',0.067,'',''],
  ['crayon',null,'a crayon',0.092,'standard size',''],
  ['mug',null,'a coffee mug',0.095,'typical 11-ounce mug','Coffee mug'],
  ['sodacan',null,'a 12-ounce soda can',0.122,'','Soda can'],
  ['pencil',null,'a pencil',0.19,'unsharpened',''],
  ['chihuahua',null,'a Chihuahua',0.305,'standing, ground to the top of its ears',''],
  ['paper',null,'a sheet of letter paper',0.279,'standing on its short edge','Letter paper'],
  ['winebottle',null,'a wine bottle',0.3,'standard 750 ml bottle','Wine bottle'],
  ['ruler',null,'a 12-inch ruler',0.305,'standing on end','Ruler'],
  ['bowlingpin',null,'a bowling pin',0.381,'',''],
  ['suitcase',null,'a carry-on suitcase',0.56,'common airline size limit','Carry-on suitcase'],
  ['labrador','🦮','a Labrador retriever',0.76,'standing, ground to the top of its ears','Labrador'],
  ['cone',null,'a highway traffic cone',0.71,'','Traffic cone'],
  ['macaw',null,'a scarlet macaw',0.84,'including its long tail','Scarlet macaw'],
  ['zeus',null,'Zeus, the tallest dog on record',1.37,'standing, ground to the top of his ears (approximate)','Zeus (Great Dane)'],
  ['hockeygoal',null,'a hockey goal',1.22,'',''],
  ['ostrich',null,'a male ostrich',2.4,'','Ostrich'],
  ['highjump',null,'the men\'s high jump world record',2.45,'bar height, set in 1993','High jump record'],
  ['container',null,'a shipping container',2.59,'standard 8 ft 6 in',''],
  ['cessna',null,'a Cessna 172 plane',2.72,'','Cessna 172'],
  ['semitruck','🚛','a semi-truck',4.11,'common US height limit','Semi-truck'],
  ['routemaster',null,'a London double-decker bus',4.38,'classic Routemaster','Double-decker bus'],
  ['diving',null,'an Olympic diving platform',10,'top platform','Diving platform'],
  ['greenmonster',null,'the Green Monster at Fenway Park',11.33,'','Green Monster'],
  ['goalpost',null,'an NFL goalpost',13.7,'crossbar plus uprights','NFL goalpost'],
  ['b747',null,'a Boeing 747-8 jet',19.5,'to the top of the tail','Boeing 747-8'],
  ['brandenburg',null,'the Brandenburg Gate',26,'including the statue on top','Brandenburg Gate'],
  ['whitetower',null,'the White Tower at the Tower of London',27,'','White Tower'],
  ['elcastillo',null,'El Castillo at Chichén Itzá',30,'including the temple on top','El Castillo'],
  ['arctriomphe',null,'the Arc de Triomphe',49.5,'','Arc de Triomphe'],
  ['horseshoe',null,'Horseshoe Falls at Niagara',51,'total drop','Horseshoe Falls'],
  ['hatteras',null,'the Cape Hatteras Lighthouse',60.5,'','Cape Hatteras Light'],
  ['towerbridge',null,'Tower Bridge in London',65,'its towers','Tower Bridge'],
  ['falcon9',null,'a Falcon 9 rocket',70,'','Falcon 9'],
  ['flatiron',null,'the Flatiron Building',93.6,'','Flatiron Building'],
  ['sls',null,'an SLS moon rocket',98,'with the Orion capsule','SLS rocket'],
  ['atomium',null,'the Atomium',102,'','Atomium'],
  ['victoriafalls',null,'Victoria Falls',108,'total drop','Victoria Falls'],
  ['harbourbridge',null,'the Sydney Harbour Bridge',134,'top of the arch, above the water','Sydney Harbour Bridge'],
  ['blackpool',null,'Blackpool Tower',158.1,'','Blackpool Tower'],
  ['flagpole',null,'the Jeddah Flagpole',171,'','Jeddah Flagpole'],
  ['gherkin',null,'the Gherkin in London',180,'','The Gherkin'],
  ['threegorges',null,'the Three Gorges Dam',181,'','Three Gorges Dam'],
  ['hoover',null,'the Hoover Dam',221.4,'','Hoover Dam'],
  ['transamerica',null,'the Transamerica Pyramid',260,'','Transamerica Pyramid'],
  ['devilstower',null,'Devils Tower',264,'summit to base','Devils Tower'],
  ['shard',null,'the Shard in London',309.6,'','The Shard'],
  ['chrysler',null,'the Chrysler Building',319,'','Chrysler Building'],
  ['burjalarab',null,'the Burj Al Arab',321,'','Burj Al Arab'],
  ['skytower',null,'the Sky Tower in Auckland',328,'','Sky Tower'],
  ['macau',null,'Macau Tower',338,'','Macau Tower'],
  ['uluru',null,'Uluru',348,'above the surrounding plain','Uluru'],
  ['strat',null,'the Strat tower in Las Vegas',350.2,'','The Strat'],
  ['berlintv',null,'the Berlin TV Tower',368,'','Berlin TV Tower'],
  ['sugarloaf',null,'Sugarloaf Mountain in Rio',396,'above the harbor','Sugarloaf Mountain'],
  ['willis',null,'the Willis Tower',442.1,'to the roof','Willis Tower'],
  ['petronas',null,'the Petronas Towers',451.9,'','Petronas Towers'],
  ['lakhta',null,'the Lakhta Center',462,'','Lakhta Center'],
  ['taipei101',null,'Taipei 101',508,'','Taipei 101'],
  ['ostankino',null,'Ostankino Tower',540.1,'','Ostankino Tower'],
  ['lotte',null,'Lotte World Tower',554.5,'','Lotte World Tower'],
  ['pingan',null,'the Ping An Finance Centre',599.1,'','Ping An Finance Centre'],
  ['canton',null,'Canton Tower',602,'','Canton Tower'],
  ['kvly',null,'the KVLY-TV mast',605.6,'','KVLY-TV mast'],
  ['shanghai',null,'Shanghai Tower',632,'','Shanghai Tower'],
  ['merdeka',null,'Merdeka 118',678.9,'','Merdeka 118'],
  ['yosemitefalls',null,'Yosemite Falls',739,'total drop','Yosemite Falls'],
  ['elcapitan',null,'El Capitan',914,'base to summit','El Capitan'],
  ['angelfalls',null,'Angel Falls',979,'total drop, the tallest waterfall','Angel Falls'],
  ['tablemtn',null,'Table Mountain',1085,'above sea level','Table Mountain'],
  ['bennevis',null,'Ben Nevis',1345,'above sea level','Ben Nevis'],
  ['mtwashington',null,'Mount Washington',1917,'above sea level','Mount Washington'],
  ['kosciuszko',null,'Mount Kosciuszko',2228,'above sea level','Mount Kosciuszko'],
  ['sthelens',null,'Mount St. Helens',2549,'above sea level','Mount St. Helens'],
  ['olympus',null,'Mount Olympus in Greece',2918,'above sea level','Mount Olympus'],
  ['kinabalu',null,'Mount Kinabalu',4095,'above sea level','Mount Kinabalu'],
  ['maunakea',null,'Mauna Kea',4207,'above sea level','Mauna Kea'],
  ['rainier',null,'Mount Rainier',4392,'above sea level','Mount Rainier'],
  ['whitney',null,'Mount Whitney',4421,'above sea level','Mount Whitney'],
  ['matterhorn',null,'the Matterhorn',4478,'above sea level','Matterhorn'],
  ['kenya',null,'Mount Kenya',5199,'above sea level','Mount Kenya'],
  ['elbrus',null,'Mount Elbrus',5642,'above sea level','Mount Elbrus'],
  ['kilimanjaro',null,'Mount Kilimanjaro',5895,'above sea level','Kilimanjaro'],
  ['denali',null,'Denali',6190,'above sea level','Denali'],
  ['aconcagua',null,'Aconcagua',6961,'above sea level','Aconcagua'],
  ['k2',null,'K2',8611,'above sea level','K2'],
  ['olympusmons',null,'Olympus Mons on Mars',21287,'above the Martian datum','Olympus Mons (Mars)'],
  ],
    RAW3: [
  ['marble',null,'a glass marble',0.016,'common size','Marble'],
  ['puck',null,'a hockey puck',0.0254,'lying flat',''],
  ['aaa',null,'an AAA battery',0.0445,'','AAA battery'],
  ['ninevolt',null,'a 9-volt battery',0.0485,'','9-volt battery'],
  ['golftee',null,'a golf tee',0.054,'standard length',''],
  ['cube',null,'a 3×3 puzzle cube',0.057,'standard size','Puzzle cube'],
  ['dbattery',null,'a D battery',0.0615,'','D battery'],
  ['ostrichegg',null,'an ostrich egg',0.15,'standing on end',''],
  ['paperback',null,'a paperback book',0.175,'mass-market size, standing up','Paperback book'],
  ['bowlingball',null,'a bowling ball',0.218,'',''],
  ['cat','🐈','a house cat',0.335,'standing, ground to the top of its ears','House cat'],
  ['racket',null,'a tennis racket',0.686,'standing on end, standard length','Tennis racket'],
  ['desk',null,'an office desk',0.74,'standard height','Desk'],
  ['washer',null,'a washing machine',0.85,'typical front-loader','Washing machine'],
  ['bat',null,'a baseball bat',0.864,'34-inch bat, standing on end','Baseball bat'],
  ['counter',null,'a kitchen counter',1.097,'floor to the top of the visible backsplash','Kitchen counter'],
  ['hurdle',null,'a 110-meter hurdle',1.067,'men\'s race height','Hurdle'],
  ['tennisnet',null,'a tennis net',1.07,'at the posts','Tennis net'],
  ['beam',null,'a gymnastics balance beam',1.25,'','Balance beam'],
  ['vending',null,'a vending machine',1.83,'typical height','Vending machine'],
  ['rover',null,'the Perseverance Mars rover',2.2,'','Perseverance rover'],
  ['abrams',null,'an M1 Abrams tank',2.44,'','M1 Abrams tank'],
  ['wrightflyer',null,'the 1903 Wright Flyer',2.74,'','Wright Flyer'],
  ['clockface',null,'one of Big Ben\'s clock faces',6.9,'diameter','Big Ben clock face'],
  ['apollolm',null,'an Apollo lunar module',7.04,'','Apollo lunar module'],
  ['minetruck',null,'a Caterpillar 797F mining truck',7.44,'bed down','Mining truck'],
  ['greatwall',null,'the Great Wall of China',7.8,'near Badaling','Great Wall'],
  ['delicatearch',null,'Delicate Arch in Utah',16,'','Delicate Arch'],
  ['orbiter',null,'a Space Shuttle orbiter',17.86,'on its landing gear','Shuttle orbiter'],
  ['an225',null,'the An-225 Mriya plane',18.1,'the largest plane ever built','An-225 Mriya'],
  ['luxor',null,'the Luxor Obelisk in Paris',23,'without its pedestal','Luxor Obelisk'],
  ['gatewayindia',null,'the Gateway of India',26,'','Gateway of India'],
  ['belem',null,'Belém Tower in Lisbon',30,'','Belém Tower'],
  ['gullfoss',null,'Gullfoss waterfall',32,'total drop','Gullfoss'],
  ['hindenburg',null,'the Hindenburg airship',41,'its diameter','Hindenburg'],
  ['seljalandsfoss',null,'Seljalandsfoss waterfall',60,'single drop','Seljalandsfoss'],
  ['spasskaya',null,'the Kremlin\'s Spasskaya Tower',71,'with its star','Spasskaya Tower'],
  ['iguazu',null,'Iguazu Falls',82,'tallest drop','Iguazu Falls'],
  ['brooklyn',null,'the Brooklyn Bridge',85,'its towers, above the water','Brooklyn Bridge'],
  ['capitol',null,'the US Capitol',88,'','US Capitol'],
  ['bagger',null,'Bagger 288, a giant excavator',96,'','Bagger 288'],
  ['dover',null,'the White Cliffs of Dover',110,'at their highest','White Cliffs of Dover'],
  ['wembley',null,'the Wembley Stadium arch',134,'','Wembley arch'],
  ['multnomah',null,'Multnomah Falls',189,'total drop','Multnomah Falls'],
  ['moher',null,'the Cliffs of Moher',214,'at their highest','Cliffs of Moher'],
  ['kaieteur',null,'Kaieteur Falls',226,'single drop','Kaieteur Falls'],
  ['americas',null,'the Tower of the Americas',229,'','Tower of the Americas'],
  ['woolworth',null,'the Woolworth Building',241,'','Woolworth Building'],
  ['millau',null,'the Millau Viaduct',343,'to the top of its tallest mast','Millau Viaduct'],
  ['bankofchina',null,'the Bank of China Tower',367.4,'','Bank of China Tower'],
  ['kltower',null,'the Kuala Lumpur Tower',421,'','KL Tower'],
  ['park432',null,'432 Park Avenue',425.5,'','432 Park Avenue'],
  ['orientalpearl',null,'the Oriental Pearl Tower',468,'','Oriental Pearl Tower'],
  ['shiprock',null,'Shiprock',482,'above the surrounding plain','Shiprock'],
  ['preikestolen',null,'Preikestolen (Pulpit Rock)',604,'above the fjord','Preikestolen'],
  ['scafell',null,'Scafell Pike',978,'above sea level','Scafell Pike'],
  ['tugela',null,'Tugela Falls',983,'total drop','Tugela Falls'],
  ['snowdon',null,'Snowdon',1085,'above sea level','Snowdon'],
  ['trollwall',null,'the Troll Wall',1100,'base to summit','Troll Wall'],
  ['diablo',null,'Mount Diablo',1173,'above sea level','Mount Diablo'],
  ['thor',null,'Mount Thor\'s cliff',1200,'the greatest vertical drop on Earth','Mount Thor'],
  ['mansfield',null,'Mount Mansfield',1339,'above sea level','Mount Mansfield'],
  ['grandcanyon',null,'the Grand Canyon\'s walls',1857,'rim to river, at the deepest point','Grand Canyon'],
  ['mitchell',null,'Mount Mitchell',2037,'above sea level','Mount Mitchell'],
  ['olympuswa',null,'Mount Olympus in Washington',2432,'above sea level','Mount Olympus (WA)'],
  ['hood',null,'Mount Hood',3429,'above sea level','Mount Hood'],
  ['teide',null,'Mount Teide',3715,'above sea level','Mount Teide'],
  ['aoraki',null,'Aoraki / Mount Cook',3724,'above sea level','Aoraki / Mount Cook'],
  ['maunaloa',null,'Mauna Loa',4169,'above sea level','Mauna Loa'],
  ['pikes',null,'Pikes Peak',4302,'above sea level','Pikes Peak'],
  ['shasta',null,'Mount Shasta',4322,'above sea level','Mount Shasta'],
  ['vinson',null,'Mount Vinson',4892,'above sea level','Mount Vinson'],
  ['ararat',null,'Mount Ararat',5137,'above sea level','Mount Ararat'],
  ['logan',null,'Mount Logan',5959,'above sea level','Mount Logan'],
  ['lhotse',null,'Lhotse',8516,'above sea level','Lhotse'],
  ['kangchenjunga',null,'Kangchenjunga',8586,'above sea level','Kangchenjunga'],
  ],
    RAW4: [
  ['cbattery',null,'a C battery',0.05,'','C battery'],
  ['brick',null,'a standard brick',0.0572,'US modular size, lying flat','Brick'],
  ['stickynote',null,'a sticky note',0.0762,'standard 3-inch square','Sticky note'],
  ['creditcard',null,'a credit card',0.0856,'standing on its short edge','Credit card'],
  ['sputnik',null,'Sputnik 1',0.58,'ground to the top of the visible satellite artwork','Sputnik 1'],
  ['stumps',null,'a set of cricket stumps',0.711,'standard 28 inches','Cricket stumps'],
  ['ttable',null,'a ping-pong table',0.76,'playing surface, net not included','Ping-pong table'],
  ['greatdane',null,'a Great Dane',1.13,'male, standing, ground to the top of its ears','Great Dane'],
  ['lrv',null,'the Apollo Lunar Roving Vehicle',1.1,'','Lunar rover'],
  ['sarus',null,'a sarus crane',1.4,'standing, typical adult','Sarus crane'],
  ['okapi',null,'an okapi',1.65,'standing, ground to the top of its ears',''],
  ['badminton',null,'a badminton net',1.55,'at the posts','Badminton net'],
  ['emu',null,'an emu',1.7,'standing, typical adult',''],
  ['moose','🫎','a moose',2.44,'standing, ground to the top of its antlers',''],
  ['vnet',null,'a volleyball net',2.43,'men\'s height','Volleyball net'],
  ['phonebox',null,'a red telephone box',2.51,'classic K6 kiosk','Red phone box'],
  ['f35',null,'an F-35 fighter jet',4.39,'','F-35 jet'],
  ['b2',null,'a B-2 stealth bomber',5.18,'on its landing gear','B-2 bomber'],
  ['sr71',null,'an SR-71 Blackbird',5.64,'on its landing gear','SR-71 Blackbird'],
  ['giantscauseway',null,'the tallest column at the Giant\'s Causeway',12,'basalt columns, Northern Ireland','Giant\'s Causeway'],
  ['b737',null,'a Boeing 737',12.55,'737-800','Boeing 737'],
  ['v2',null,'a V-2 rocket',14,'','V-2 rocket'],
  ['blimp',null,'a Zeppelin NT airship',17.4,'','Zeppelin NT airship'],
  ['rhinefalls',null,'the Rhine Falls',23,'Switzerland','Rhine Falls'],
  ['dettifoss',null,'Dettifoss',44,'Iceland','Dettifoss'],
  ['twelveapostles',null,'the tallest of the Twelve Apostles',45,'sea stack, Australia','Twelve Apostles'],
  ['soyuz',null,'a Soyuz rocket',46.3,'Soyuz-2','Soyuz rocket'],
  ['pontdugard',null,'the Pont du Gard',48.8,'Roman aqueduct, France','Pont du Gard'],
  ['nelson',null,'Nelson\'s Column',51.6,'including the statue','Nelson\'s Column'],
  ['hercules',null,'the Tower of Hercules',55,'Roman lighthouse, Spain','Tower of Hercules'],
  ['skogafoss',null,'Skógafoss',60,'Iceland','Skógafoss'],
  ['ariane6',null,'an Ariane 6 rocket',62,'four-booster version','Ariane 6'],
  ['djoser',null,'the Pyramid of Djoser',62.5,'original height','Pyramid of Djoser'],
  ['shoshone',null,'Shoshone Falls',65,'Idaho','Shoshone Falls'],
  ['peritomoreno',null,'the ice wall of Perito Moreno Glacier',74,'average height above the lake','Perito Moreno Glacier'],
  ['plitvice',null,'Veliki Slap at Plitvice',78,'Croatia','Veliki Slap (Plitvice)'],
  ['rainbowbridge',null,'Rainbow Bridge in Utah',88,'natural stone arch','Rainbow Bridge'],
  ['newglenn',null,'a New Glenn rocket',98,'','New Glenn rocket'],
  ['fury325',null,'the Fury 325 roller coaster',102,'ground to the top of the decorative marker above the lift hill (approximate)','Fury 325 coaster'],
  ['redpyramid',null,'the Red Pyramid',105,'Egypt','Red Pyramid'],
  ['bassrock',null,'Bass Rock',107,'island, Scotland','Bass Rock'],
  ['forthbridge',null,'the Forth Bridge',110,'above high water','Forth Bridge'],
  ['topthrill',null,'the Top Thrill 2 roller coaster',128,'','Top Thrill 2 coaster'],
  ['oldmanofhoy',null,'the Old Man of Hoy',137,'sea stack, Scotland','Old Man of Hoy'],
  ['jetdeau',null,'Geneva\'s Jet d\'Eau fountain',140,'height of the jet','Jet d\'Eau'],
  ['dubaiframe',null,'the Dubai Frame',150.24,'','Dubai Frame'],
  ['beachyhead',null,'Beachy Head',162,'chalk cliff, England','Beachy Head'],
  ['grandcoulee',null,'the Grand Coulee Dam',168,'','Grand Coulee Dam'],
  ['reunion',null,'Reunion Tower in Dallas',171,'','Reunion Tower'],
  ['sanjacinto',null,'the San Jacinto Monument',172.9,'including the star','San Jacinto Monument'],
  ['sigiriya',null,'Sigiriya rock',180,'above the plain, Sri Lanka','Sigiriya'],
  ['kuwaittowers',null,'the main Kuwait Tower',187,'','Kuwait Towers'],
  ['euromast',null,'the Euromast',184.6,'Rotterdam','Euromast'],
  ['bridalveil',null,'Bridalveil Fall',188,'Yosemite','Bridalveil Fall'],
  ['turningtorso',null,'the Turning Torso',190,'Malmö','Turning Torso'],
  ['itaipu',null,'the Itaipu Dam',196,'','Itaipu Dam'],
  ['stacanarmin',null,'Stac an Armin',196,'sea stack, St Kilda','Stac an Armin'],
  ['verrazzano',null,'the Verrazzano-Narrows Bridge',211,'tower height','Verrazzano Bridge'],
  ['contra',null,'the Contra Dam',220,'Switzerland','Contra Dam'],
  ['seoultower',null,'N Seoul Tower',236.7,'','N Seoul Tower'],
  ['jogfalls',null,'Jog Falls',253,'India','Jog Falls'],
  ['olympiaturm',null,'the Olympic Tower in Munich',291,'','Olympiaturm'],
  ['akashi',null,'the Akashi Kaikyō Bridge',298.3,'tower height above the sea','Akashi Kaikyō Bridge'],
  ['kingdomcentre',null,'the Kingdom Centre in Riyadh',302.3,'','Kingdom Centre'],
  ['jinping',null,'the Jinping-I Dam',305,'the world\'s tallest dam','Jinping-I Dam'],
  ['sydneytower',null,'Sydney Tower',309,'including the spire','Sydney Tower'],
  ['salesforce',null,'Salesforce Tower',326,'San Francisco','Salesforce Tower'],
  ['ailsacraig',null,'Ailsa Craig',338,'island, Scotland','Ailsa Craig'],
  ['kyivtv',null,'the Kyiv TV Tower',385,'','Kyiv TV Tower'],
  ['hudsonyards',null,'30 Hudson Yards',387.1,'New York','30 Hudson Yards'],
  ['jinmao',null,'the Jin Mao Tower',420.5,'Shanghai','Jin Mao Tower'],
  ['gibraltar',null,'the Rock of Gibraltar',426,'','Rock of Gibraltar'],
  ['milad',null,'Milad Tower',435,'Tehran, including the mast','Milad Tower'],
  ['centralpark',null,'Central Park Tower',472.4,'New York','Central Park Tower'],
  ['swfc',null,'the Shanghai World Financial Center',492,'','Shanghai World Financial Center'],
  ['ballspyramid',null,'Ball\'s Pyramid',572,'sea stack, Australia','Ball\'s Pyramid'],
  ['sutherland',null,'Sutherland Falls',580,'New Zealand','Sutherland Falls'],
  ['gocta',null,'Gocta Falls',771,'Peru, both drops','Gocta Falls'],
  ['vinnufossen',null,'Vinnufossen',845,'Norway','Vinnufossen'],
  ['zugspitze',null,'the Zugspitze',2962,'above sea level','Zugspitze'],
  ['eiger',null,'the Eiger',3967,'above sea level','Eiger'],
  ['montblanc',null,'Mont Blanc',4806,'above sea level, it shifts slightly','Mont Blanc'],
  ['cotopaxi',null,'Cotopaxi',5897,'above sea level','Cotopaxi'],
  ['chimborazo',null,'Chimborazo',6263,'above sea level','Chimborazo'],
  ['makalu',null,'Makalu',8485,'above sea level','Makalu'],
  ],
    RAW5: [
  ['polarbear',null,'a polar bear',3.05,'adult male standing on its hind legs, ground to the top of its ears','Polar bear'],
  ['gorilla','🦍','a silverback gorilla',1.7,'standing upright','Gorilla'],
  ['kangaroo','🦘','a red kangaroo',1.8,'a big male standing tall','Kangaroo'],
  ['trex','🦖','a T. rex',4,'to the top of its head, as the Sue skeleton stands','T. rex'],
  ['fridge',null,'a refrigerator',1.78,'a standard 70-inch fridge','Refrigerator'],
  ['hoop',null,'a basketball hoop',3.99,'ground to the top of the backboard (about 13 ft)','Basketball hoop'],
  ['house','🏠','a house',6,'a one-story house, ground to roof peak','House'],
  ['suv','🚙','an SUV',1.8,'a midsize SUV, to the roof','SUV'],
  ['gameboy',null,'an original Game Boy',0.148,'1989 model, standing up','Game Boy'],
  ['ipod',null,'an iPod classic',0.104,'standing up','iPod classic'],
  ],
    STD: [
  // Party expansion: everyday, sports, and recognizable tech.
  ["bowlingpin", null, "a bowling pin", 0.381 / FT, "regulation tenpin, standing upright", "Bowling Pin", "sports", 10],
  ["cone", null, "a traffic cone", 0.7112 / FT, "representative highway cone, base to tip", "Traffic Cone", "everyday", 10],
  ["suitcase", null, "a carry-on suitcase", 0.5588 / FT, "representative cabin suitcase, wheels included, handle retracted", "Carry-on Suitcase", "everyday", 9],
  ["winebottle", null, "a wine bottle", 0.3 / FT, "representative 750 ml bottle, base to top", "Wine Bottle", "everyday", 9],
  ["desk", null, "an office desk", 0.74 / FT, "representative desk, floor to desktop", "Office Desk", "everyday", 10],
  ["washer", null, "a washing machine", 0.85 / FT, "representative front-loader, overall height", "Washing Machine", "everyday", 10],
  ["counter", null, "a kitchen counter", 1.097 / FT, "floor to the top of the visible backsplash", "Kitchen Counter", "everyday", 10],
  ["ttable", null, "a ping-pong table", 0.9144 / FT, "floor to the top of the net", "Ping-pong Table", "sports", 9],
  ["hockeygoal", null, "a hockey goal", 1.2192 / FT, "regulation opening, floor to crossbar", "Hockey Goal", "sports", 9],
  ["hurdle", null, "a hurdles-race barrier", 1.067 / FT, "senior men’s 110 m race, ground to top", "Track Hurdle", "sports", 8],
  ["tennisnet", null, "a tennis net", 1.0668 / FT, "height at the posts, not the center", "Tennis Net", "sports", 10],
  ["beam", null, "a gymnastics balance beam", 1.25 / FT, "floor to top of beam", "Balance Beam", "sports", 8],
  ["ninevolt", null, "a 9-volt battery", 0.0485 / FT, "upright, terminals included", "9-Volt Battery", "tech", 9],
  ["aaa", null, "an AAA battery", 0.0445 / FT, "standing upright, end to end", "AAA Battery", "tech", 9],
  ["dbattery", null, "a D battery", 0.0615 / FT, "standing upright, end to end", "D Battery", "tech", 8],
  ["paperback", null, "a paperback book", 0.175 / FT, "representative mass-market paperback, standing upright", "Paperback Book", "everyday", 9],
  ["die", "🎲", "a six-sided die", 0.016 / FT, "representative tabletop die, bottom face to top face", "Die", "everyday", 10],
  ["pingpong", null, "a ping-pong ball", 0.04 / FT, "regulation ball, bottom to top", "Ping-pong Ball", "sports", 10],
  ["mug", null, "a coffee mug", 0.095 / FT, "representative 11-ounce mug, base to rim", "Coffee Mug", "everyday", 10],
  ["sodacan", null, "a soda can", 0.122 / FT, "representative US 12-ounce can, base to top", "Soda Can", "everyday", 10],
  ["xboxseriesx", null, "an Xbox Series X", 0.301 / FT, "original disc console, standing vertically", "Xbox Series X", "tech", 10],
  ["ps5original", null, "an original PlayStation 5", 0.39 / FT, "2020 disc console, vertical body, base excluded", "Original PlayStation 5", "tech", 10],
  ["billybookcase", null, "an IKEA BILLY bookcase", 2.02 / FT, "tall standard model, no extension unit", "BILLY Bookcase", "everyday", 9],
  ["lacktable", null, "an IKEA LACK side table", 0.45 / FT, "square side-table model, floor to tabletop", "LACK Side Table", "everyday", 9],

  // everyday
  ['person', '🧍', 'a 6-foot person', 6.0, 'standing height', '6-Foot Person', 'everyday', 10],
  ['door', '🚪', 'a door', 6.67, 'a standard door, floor to the top of the frame', 'Standard Door', 'everyday', 10],
  ['fridge', null, 'a refrigerator', 5.8, 'overall height of a standard fridge', 'Refrigerator', 'everyday', 10],
  ['vending', null, 'a vending machine', 6.0, 'overall height', 'Vending Machine', 'everyday', 9],
  ['hoop', null, 'a basketball hoop', 13.0, 'ground to the top of the backboard', 'Basketball Hoop', 'everyday', 10],
  ['atm', null, 'an ATM', 5.0, 'overall height of a walk-up machine', 'ATM', 'everyday', 8],
  ['portapotty', null, 'a portable toilet', 7.5, 'overall height', 'Portable Toilet', 'everyday', 8],
  ['container', null, 'a shipping container', 8.5, 'standard container sitting on the ground', 'Shipping Container', 'everyday', 8],
  // pop culture — canonical on-screen/toy heights, rounded for quick party-game comparisons
  ['spongebob', '🧽', 'SpongeBob SquarePants', 0.33, 'animated character height, about 4 inches', 'SpongeBob', 'popculture', 10],
  ['minion', '🟡', 'a Minion', 3.6, 'standing height', 'Minion', 'popculture', 10],
  ['r2d2', '🤖', 'R2-D2', 3.2, 'standing height', 'R2-D2', 'popculture', 10],
  ['yoda', '👽', 'Yoda', 2.17, 'standing height', 'Yoda', 'popculture', 10],
  ['et', '👽', 'E.T.', 3.0, 'standing height', 'E.T.', 'popculture', 9],
  ['gollum', '🧌', 'Gollum', 4.0, 'standing height', 'Gollum', 'popculture', 9],
  ['harrypotter', '🧙', 'Harry Potter', 5.11, 'standing height', 'Harry Potter', 'popculture', 10],
  ['wednesday', '🖤', 'Wednesday Addams', 5.1, 'standing height', 'Wednesday Addams', 'popculture', 9],
  ['hermione', '🪄', 'Hermione Granger', 5.5, 'standing height', 'Hermione Granger', 'popculture', 9],
  ['batman', '🦇', 'Batman', 6.2, 'standing height', 'Batman', 'popculture', 10],
  ['superman', '🦸', 'Superman', 6.3, 'standing height', 'Superman', 'popculture', 10],
  ['wonderwoman', '🦸‍♀️', 'Wonder Woman', 6.0, 'standing height', 'Wonder Woman', 'popculture', 9],
  ['jacksparrow', '🏴‍☠️', 'Captain Jack Sparrow', 5.10, 'standing height', 'Jack Sparrow', 'popculture', 9],
  ['kingkong', '🦍', 'King Kong', 25.0, 'standing height', 'King Kong', 'popculture', 9],
  ['godzilla', '🦖', 'Godzilla', 393.0, 'standing height in the modern film version', 'Godzilla', 'popculture', 10],
  ['groot', '🌳', 'Groot', 23.0, 'adult standing height', 'Groot', 'popculture', 9],
  ['barbie', '👱‍♀️', 'Barbie', 0.96, 'doll height, about 11.5 inches', 'Barbie', 'popculture', 10],
  ['sherlock', '🔎', 'Sherlock Holmes', 6.0, 'standing height', 'Sherlock Holmes', 'popculture', 9],
  ['dracula', '🧛', 'Dracula', 6.2, 'standing height', 'Dracula', 'popculture', 9],
  ['frankenstein', '🧟', 'Frankenstein', 8.0, 'standing height', 'Frankenstein', 'popculture', 9],
  ['dorothy', '👠', 'Dorothy', 4.5, 'standing height', 'Dorothy', 'popculture', 9],
  ['santa', '🎅', 'Santa Claus', 6.0, 'estimated standing height', 'Santa Claus', 'popculture', 10],
  // animals
  ['giraffe', '🦒', 'a giraffe', 18.0, 'adult male standing height, ground to the top of its ossicones', 'Giraffe', 'animals', 10],
  ['ostrich', null, 'an ostrich', 9.0, 'adult male standing height', 'Ostrich', 'animals', 9],
  ['elephant', '🐘', 'an African elephant', 12.0, 'adult bull, ground to the top of its head and ears', 'African Elephant', 'animals', 10],
  ['moose', null, 'a moose', 8.0, 'adult bull, ground to the top of its antlers', 'Moose', 'animals', 8],
  ['horse', '🐎', 'a horse', 6.75, 'standing, ground to the top of its ears', 'Horse', 'animals', 10],
  ['camel', '🐪', 'a camel', 7.5, 'standing, ground to the top of its ears', 'Camel', 'animals', 9],
  ['bison', '🦬', 'an American bison', 6.3, 'adult bull, ground to the top of its horns', 'American Bison', 'animals', 8],
  ['gorilla', '🦍', 'a gorilla', 5.5, 'silverback standing upright', 'Gorilla', 'animals', 9],
  ['polarbear', null, 'a polar bear', 10.0, 'adult male standing on its hind legs, ground to the top of its ears', 'Polar Bear', 'animals', 9],
  ['grizzly', null, 'a grizzly bear', 8.5, 'adult male standing on its hind legs, ground to the top of its ears', 'Grizzly Bear', 'animals', 8],
  ['kangaroo', '🦘', 'a red kangaroo', 6.0, 'adult male standing tall', 'Red Kangaroo', 'animals', 8],
  ['penguin', '🐧', 'an emperor penguin', 4.0, 'adult standing height', 'Emperor Penguin', 'animals', 8],
  ['lion', null, 'a lion', 5.25, 'adult male, ground to the top of its mane', 'Lion', 'animals', 10],
  ['tiger', '🐅', 'a tiger', 4.25, 'standing, ground to the top of its ears', 'Tiger', 'animals', 9],
  ['greatdane', null, 'a Great Dane', 3.7, 'male, standing, ground to the top of its ears', 'Great Dane', 'animals', 7],
  ['flamingo', '🦩', 'a flamingo', 4.5, 'standing height', 'Flamingo', 'animals', 8],
  // vehicles
  ['car', '🚗', 'a sedan', 4.8, 'overall vehicle height', 'Sedan', 'vehicles', 10],
  ['suv', '🚙', 'an SUV', 6.2, 'overall vehicle height', 'SUV', 'vehicles', 10],
  ['pickup', '🛻', 'a pickup truck', 6.4, 'overall vehicle height', 'Pickup Truck', 'vehicles', 10],
  ['bus', 'art:schoolbus', 'a school bus', 10.5, 'overall vehicle height', 'School Bus', 'vehicles', 10],
  ['semitruck', '🚛', 'a semi truck', 13.5, 'overall height with the trailer', 'Semi Truck', 'vehicles', 9],
  ['routemaster', null, 'a double-decker bus', 14.4, 'overall vehicle height', 'Double-Decker Bus', 'vehicles', 9],
  ['monstertruck', null, 'a monster truck', 12.0, 'overall vehicle height', 'Monster Truck', 'vehicles', 8],
  ['ambulance', '🚑', 'an ambulance', 9.0, 'overall height, lights included', 'Ambulance', 'vehicles', 9],
  ['firetruck', '🚒', 'a fire truck', 10.5, 'overall vehicle height', 'Fire Truck', 'vehicles', 9],
  // landmarks
  ['liberty', 'art:libertyfull', 'the Statue of Liberty', 305, 'ground to torch, including the pedestal', 'Statue of Liberty', 'landmarks', 10],
  ['bigben', null, 'Big Ben', 316, 'the Elizabeth Tower, to the top of its spire', 'Big Ben', 'landmarks', 10],
  ['spaceneedle', null, 'the Space Needle', 605, 'total height', 'Space Needle', 'landmarks', 9],
  ['arch', null, 'the Gateway Arch', 630, 'total height', 'Gateway Arch', 'landmarks', 8],
  ['goldengate', null, 'a Golden Gate Bridge tower', 746, 'tower height above the water', 'Golden Gate Tower', 'landmarks', 9],
  ['eiffel', null, 'the Eiffel Tower', 1083, 'total height, antennas included', 'Eiffel Tower', 'landmarks', 10],
  ['empire', null, 'the Empire State Building', 1454, 'ground to the top of its antenna', 'Empire State Building', 'landmarks', 10],
  ['onewtc', null, 'One World Trade Center', 1776, 'architectural height, spire included', 'One World Trade Center', 'landmarks', 9],
  ['burj', null, 'the Burj Khalifa', 2717, 'architectural height', 'Burj Khalifa', 'landmarks', 9],
  ['washington', null, 'the Washington Monument', 555, 'total height', 'Washington Monument', 'landmarks', 9],
  ['christ', null, 'Christ the Redeemer', 125, 'statue and pedestal', 'Christ the Redeemer', 'landmarks', 9],
  // structures and rides
  ['ferriswheel', '🎡', 'a Ferris wheel', 150, 'a typical big fairground wheel', 'Ferris Wheel', 'rides', 9],
  ['londoneye', '🎡', 'the London Eye', 443, 'total height', 'London Eye', 'rides', 8],
  ['kingdaka', 'art:topthrill', 'the Kingda Ka roller coaster', 456, 'top of the tower (the ride ran 2005-2024)', 'Kingda Ka', 'rides', 7],
  ['fury325', null, 'the Fury 325 roller coaster', 335, 'ground to the top of the decorative marker above the lift hill (approximate)', 'Fury 325', 'rides', 6],
  ['celltower', null, 'a cell tower', 150, 'a typical lattice tower', 'Cell Tower', 'rides', 8],
  ['watertower', null, 'a water tower', 130, 'a typical town water tower', 'Water Tower', 'rides', 8],
  // prehistoric
  ['trex', '🦖', 'a T. rex', 12, 'standing height, to the top of its head', 'T. rex', 'dinos', 10],
  ['raptor', '🦖', 'a Velociraptor', 3, 'standing height, to the top of its head', 'Velociraptor', 'dinos', 8],
  ['triceratops', null, 'a Triceratops', 12, 'standing, ground to the top of its horns', 'Triceratops', 'dinos', 9],
  ['stegosaurus', null, 'a Stegosaurus', 14, 'to the top of its back plates', 'Stegosaurus', 'dinos', 9],
  ],
    NOT_UPRIGHT: ['egg', 'titanic', 'a380', 'b747', 'b737', 'an225', 'cessna', 'f35', 'b2', 'sr71', 'chinook', 'blimp', 'hindenburg',
  'wrightflyer', 'orbiter', 'quarter', 'dime', 'nickel', 'creditcard', 'cd', 'paper', 'pencil', 'crayon', 'card', 'puck', 'stickynote',
  'ruler', 'bat', 'racket', 'cube', 'clockface'],
    ANCHORS: ['person', 'door', 'car', 'bus', 'house', 'liberty', 'phone', 'hoop', 'eiffel', 'giraffe', 'elephant', 'bigben']
  };
})();
