/* How Big? object catalog.
   RAW rows: [id, emoji (null = drawn art), prompt, height in meters, note, label].
   STD rows: [id, picture, prompt, height in feet, note, label, theme, familiarity (1-10)].
   Keep these values and IDs stable; game logic combines both row types into the live catalog. */
window.HOW_BIG_OBJECTS = (() => {
  const FT = 0.3048;
  return {
    RAW: [
  ['battery','🔋','an AA battery',0.0505,'',''],
  ['baseball','⚾','a baseball',0.074,'',''],
  ['softball','🥎','a softball',0.097,'',''],
  ['phone','📱','a smartphone',0.147,'standing upright',''],
  ['soccer','⚽','a soccer ball',0.22,'',''],
  ['basketball','🏀','a basketball',0.24,'',''],
  ['trophy','🏆','the FIFA World Cup trophy',0.368,'','World Cup trophy'],
  ['bucket','🪣','a 5-gallon bucket',0.37,'','Bucket'],
  ['toilet','🚽','a toilet',0.76,'',''],
  ['chair','🪑','a dining chair',0.9,'',''],
  ['tiger','🐅','a Bengal tiger',1.30,'standing, ground to the top of its ears','Tiger'],
  ['penguin','🐧','an emperor penguin',1.0,'standing','Emperor penguin'],
  ['bike','🚲','a bicycle',1.0,'',''],
  ['flamingo','🦩','a flamingo',1.3,'',''],
  ['hippo','🦛','a hippo',1.55,'standing, ground to the top of its ears',''],
  ['car','🚗','a compact car',1.44,'',''],
  ['cow','🐄','a Holstein cow',1.68,'standing, ground to the top of its head and horns','Cow'],
  ['horse','🐎','a horse',2.06,'standing, ground to the top of its ears',''],
  ['person','🧍','an adult person',1.7,'',''],
  ['rhino','🦏','a white rhino',1.98,'standing, ground to the top of its horn',''],
  ['bison','🦬','an American bison',1.92,'standing, ground to the top of its horns','Bison'],
  ['pickup','🛻','a full-size pickup truck',1.96,'','Pickup truck'],
  ['door','🚪','a door',2.03,'',''],
  ['camel','🐪','a camel',2.29,'standing, ground to the top of its ears',''],
  ['xmastree','🎄','a 7.5-foot Christmas tree',2.29,'','Christmas tree'],
  ['goal','🥅','a soccer goal',2.44,'',''],
  ['mammoth','🦣','a woolly mammoth',3.66,'standing, ground to the top of its head',''],
  ['elephant','🐘','an African elephant',3.66,'adult bull, ground to the top of its head and ears','Elephant'],
  ['bus','🚌','a city bus',3.2,'',''],
  ['giraffe','🦒','a male giraffe',5.49,'standing, ground to the top of its ossicones','Giraffe'],
  ['stonehenge',null,'the tallest stone at Stonehenge',6.7,'above ground','Stonehenge'],
  ['brachio','🦕','a Brachiosaurus',12,'with its head raised',''],
  ['hollywood',null,'the Hollywood sign',13.4,'letter height','Hollywood sign'],
  ['sphinx',null,'the Great Sphinx of Giza',20,'','Great Sphinx'],
  ['christ',null,'Christ the Redeemer',38,'including its pedestal','Christ the Redeemer'],
  ['liberty','🗽','the Statue of Liberty',46,'heel to torch, without the pedestal','Statue of Liberty'],
  ['colosseum',null,'the Colosseum',48,'outer wall','Colosseum'],
  ['pisa',null,'the Leaning Tower of Pisa',61.6,'ground to the top of the flag on its high side (approximate)','Tower of Pisa'],
  ['taj',null,'the Taj Mahal',73,'','Taj Mahal'],
  ['bigben',null,'Big Ben',96,'the Elizabeth Tower','Big Ben'],
  ['saturnv',null,'a Saturn V rocket',111,'','Saturn V rocket'],
  ['hyperion','🌲','Hyperion, the world\'s tallest tree',116,'a coast redwood','Hyperion (redwood)'],
  ['londoneye','🎡','the London Eye',135,'','London Eye'],
  ['pyramid',null,'the Great Pyramid of Giza',138.5,'as it stands today','Great Pyramid'],
  ['washington',null,'the Washington Monument',169,'','Washington Monument'],
  ['spaceneedle',null,'the Space Needle',184,'','Space Needle'],
  ['arch',null,'the Gateway Arch',192,'','Gateway Arch'],
  ['goldengate',null,'a Golden Gate Bridge tower',227,'above the water','Golden Gate tower'],
  ['eiffel',null,'the Eiffel Tower',330,'','Eiffel Tower'],
  ['empire',null,'the Empire State Building',443,'ground to the top of its antenna','Empire State Building'],
  ['onewtc',null,'One World Trade Center',541,'','One World Trade Center'],
  ['cntower',null,'the CN Tower',553,'','CN Tower'],
  ['burj',null,'the Burj Khalifa',828,'','Burj Khalifa'],
  ['fuji','🗻','Mount Fuji',3776,'above sea level','Mount Fuji'],
  ['everest','🏔️','Mount Everest',8849,'above sea level','Mount Everest'],
  ['dangi',null,'Chandra Bahadur Dangi, the shortest adult on record',0.61,'standing, ground to the top of his hat','Chandra Bahadur Dangi'],
  ['biles',null,'Simone Biles',1.65,'in the pictured pose, ground to the top of her raised fingers','Simone Biles'],
  ['bogues',null,'Muggsy Bogues',1.6,'listed height','Muggsy Bogues'],
  ['messi',null,'Lionel Messi',1.7,'listed height','Lionel Messi'],
  ['curry',null,'Stephen Curry',1.88,'listed height','Stephen Curry'],
  ['lebron',null,'LeBron James',2.06,'listed height','LeBron James'],
  ['shaq',null,"Shaquille O'Neal",2.16,'listed height',"Shaquille O'Neal"],
  ['wemby',null,'Victor Wembanyama',2.24,'listed height','Victor Wembanyama'],
  ['yao',null,'Yao Ming',2.29,'listed height','Yao Ming'],
  ['wadlow',null,'Robert Wadlow, the tallest person on record',2.72,'Guinness World Record','Robert Wadlow'],
  ['shuttle',null,'a Space Shuttle on the launch pad',56,'full launch stack','Space Shuttle'],
  ],
    RAW2: [
  ['die','🎲','a six-sided die',0.016,'standard size','Die'],
  ['pingpong',null,'a ping-pong ball',0.04,'',''],
  ['golfball',null,'a golf ball',0.0427,'',''],
  ['tennisball',null,'a tennis ball',0.067,'',''],
  ['mug',null,'a coffee mug',0.095,'typical 11-ounce mug','Coffee mug'],
  ['sodacan',null,'a 12-ounce soda can',0.122,'','Soda can'],
  ['chihuahua',null,'a Chihuahua',0.305,'standing, ground to the top of its ears',''],
  ['winebottle',null,'a wine bottle',0.3,'standard 750 ml bottle','Wine bottle'],
  ['bowlingpin',null,'a bowling pin',0.381,'',''],
  ['suitcase',null,'a carry-on suitcase',0.56,'common airline size limit','Carry-on suitcase'],
  ['labrador','🦮','a Labrador retriever',0.76,'standing, ground to the top of its ears','Labrador'],
  ['cone',null,'a highway traffic cone',0.71,'','Traffic cone'],
  ['hockeygoal',null,'a hockey goal',1.22,'',''],
  ['ostrich',null,'a male ostrich',2.4,'','Ostrich'],
  ['container',null,'a shipping container',2.59,'standard 8 ft 6 in',''],
  ['semitruck','🚛','a semi-truck',4.11,'common US height limit','Semi-truck'],
  ['routemaster',null,'a London double-decker bus',4.38,'classic Routemaster','Double-decker bus'],
  ['falcon9',null,'a Falcon 9 rocket',70,'','Falcon 9'],
  ['sls',null,'an SLS moon rocket',98,'with the Orion capsule','SLS rocket'],
  ],
    RAW3: [
  ['marble',null,'a glass marble',0.016,'common size','Marble'],
  ['aaa',null,'an AAA battery',0.0445,'','AAA battery'],
  ['ninevolt',null,'a 9-volt battery',0.0485,'','9-volt battery'],
  ['dbattery',null,'a D battery',0.0615,'','D battery'],
  ['paperback',null,'a paperback book',0.175,'mass-market size, standing up','Paperback book'],
  ['cat','🐈','a house cat',0.335,'standing, ground to the top of its ears','House cat'],
  ['desk',null,'an office desk',0.74,'standard height','Desk'],
  ['washer',null,'a washing machine',0.85,'typical front-loader','Washing machine'],
  ['counter',null,'a kitchen counter',1.097,'floor to the top of the visible backsplash','Kitchen counter'],
  ['hurdle',null,'a 110-meter hurdle',1.067,'men\'s race height','Hurdle'],
  ['tennisnet',null,'a tennis net',1.07,'at the posts','Tennis net'],
  ['beam',null,'a gymnastics balance beam',1.25,'','Balance beam'],
  ['vending',null,'a vending machine',1.83,'typical height','Vending machine'],
  ],
    RAW4: [
  ['ttable',null,'a ping-pong table',0.76,'playing surface, net not included','Ping-pong table'],
  ['greatdane',null,'a Great Dane',1.13,'male, standing, ground to the top of its ears','Great Dane'],
  ['moose','🫎','a moose',2.44,'standing, ground to the top of its antlers',''],
  ['fury325',null,'the Fury 325 roller coaster',102,'ground to the top of the decorative marker above the lift hill (approximate)','Fury 325 coaster'],
  ],
    RAW5: [
  ['polarbear',null,'a polar bear',3.05,'adult male standing on its hind legs, ground to the top of its ears','Polar bear'],
  ['gorilla','🦍','a silverback gorilla',1.7,'standing upright','Gorilla'],
  ['kangaroo','🦘','a red kangaroo',1.8,'a big male standing tall','Kangaroo'],
  ['trex','🦖','a T. rex',4,'to the top of its head, as the Sue skeleton stands','T. rex'],
  ['fridge',null,'a refrigerator',1.78,'a standard 70-inch fridge','Refrigerator'],
  ['hoop',null,'a basketball hoop',3.99,'ground to the top of the backboard (about 13 ft)','Basketball hoop'],
  ['house','🏠','a house',6,'a one-story house, ground to roof peak','House'],
  ['suv','🚙','an SUV',1.8,'a midsize SUV, to the roof','SUV'],
  ['gameboy',null,'an original Game Boy',0.148,'1989 model, standing up','Game Boy'],
  ['ipod',null,'an iPod classic',0.104,'standing up','iPod classic'],
  ],
    STD: [
  // Party expansion: everyday, sports, and recognizable tech.
  ["bowlingpin", null, "a bowling pin", 0.381 / FT, "regulation tenpin, standing upright", "Bowling Pin", "sports", 10],
  ["cone", null, "a traffic cone", 0.7112 / FT, "representative highway cone, base to tip", "Traffic Cone", "everyday", 10],
  ["suitcase", null, "a carry-on suitcase", 0.5588 / FT, "representative cabin suitcase, wheels included, handle retracted", "Carry-on Suitcase", "everyday", 9],
  ["winebottle", null, "a wine bottle", 0.3 / FT, "representative 750 ml bottle, base to top", "Wine Bottle", "everyday", 9],
  ["desk", null, "an office desk", 0.74 / FT, "representative desk, floor to desktop", "Office Desk", "everyday", 10],
  ["washer", null, "a washing machine", 0.85 / FT, "representative front-loader, overall height", "Washing Machine", "everyday", 10],
  ["counter", null, "a kitchen counter", 1.097 / FT, "floor to the top of the visible backsplash", "Kitchen Counter", "everyday", 10],
  ["ttable", null, "a ping-pong table", 0.9144 / FT, "floor to the top of the net", "Ping-pong Table", "sports", 9],
  ["hockeygoal", null, "a hockey goal", 1.2192 / FT, "regulation opening, floor to crossbar", "Hockey Goal", "sports", 9],
  ["hurdle", null, "a hurdles-race barrier", 1.067 / FT, "senior men’s 110 m race, ground to top", "Track Hurdle", "sports", 8],
  ["tennisnet", null, "a tennis net", 1.0668 / FT, "height at the posts, not the center", "Tennis Net", "sports", 10],
  ["beam", null, "a gymnastics balance beam", 1.25 / FT, "floor to top of beam", "Balance Beam", "sports", 8],
  ["ninevolt", null, "a 9-volt battery", 0.0485 / FT, "upright, terminals included", "9-Volt Battery", "tech", 9],
  ["aaa", null, "an AAA battery", 0.0445 / FT, "standing upright, end to end", "AAA Battery", "tech", 9],
  ["dbattery", null, "a D battery", 0.0615 / FT, "standing upright, end to end", "D Battery", "tech", 8],
  ["paperback", null, "a paperback book", 0.175 / FT, "representative mass-market paperback, standing upright", "Paperback Book", "everyday", 9],
  ["die", "🎲", "a six-sided die", 0.016 / FT, "representative tabletop die, bottom face to top face", "Die", "everyday", 10],
  ["pingpong", null, "a ping-pong ball", 0.04 / FT, "regulation ball, bottom to top", "Ping-pong Ball", "sports", 10],
  ["mug", null, "a coffee mug", 0.095 / FT, "representative 11-ounce mug, base to rim", "Coffee Mug", "everyday", 10],
  ["sodacan", null, "a soda can", 0.122 / FT, "representative US 12-ounce can, base to top", "Soda Can", "everyday", 10],
  ["xboxseriesx", null, "an Xbox Series X", 0.301 / FT, "original disc console, standing vertically", "Xbox Series X", "tech", 10],
  ["ps5original", null, "an original PlayStation 5", 0.39 / FT, "2020 disc console, vertical body, base excluded", "Original PlayStation 5", "tech", 10],
  ["billybookcase", null, "an IKEA BILLY bookcase", 2.02 / FT, "tall standard model, no extension unit", "BILLY Bookcase", "everyday", 9],
  ["lacktable", null, "an IKEA LACK side table", 0.45 / FT, "square side-table model, floor to tabletop", "LACK Side Table", "everyday", 9],

  // everyday
  ['person', '🧍', 'a 6-foot person', 6.0, 'standing height', '6-Foot Person', 'everyday', 10],
  ['door', '🚪', 'a door', 6.67, 'a standard door, floor to the top of the frame', 'Standard Door', 'everyday', 10],
  ['fridge', null, 'a refrigerator', 5.8, 'overall height of a standard fridge', 'Refrigerator', 'everyday', 10],
  ['vending', null, 'a vending machine', 6.0, 'overall height', 'Vending Machine', 'everyday', 9],
  ['hoop', null, 'a basketball hoop', 13.0, 'ground to the top of the backboard', 'Basketball Hoop', 'everyday', 10],
  ['atm', null, 'an ATM', 5.0, 'overall height of a walk-up machine', 'ATM', 'everyday', 8],
  ['portapotty', null, 'a portable toilet', 7.5, 'overall height', 'Portable Toilet', 'everyday', 8],
  ['container', null, 'a shipping container', 8.5, 'standard container sitting on the ground', 'Shipping Container', 'everyday', 8],
  // pop culture — canonical on-screen/toy heights, rounded for quick party-game comparisons
  ['spongebob', '🧽', 'SpongeBob SquarePants', 0.33, 'animated character height, about 4 inches', 'SpongeBob', 'popculture', 10],
  ['r2d2', '🤖', 'R2-D2', 3.2, 'standing height', 'R2-D2', 'popculture', 10],
  ['et', '👽', 'E.T.', 3.0, 'standing height', 'E.T.', 'popculture', 9],
  ['gollum', '🧌', 'Gollum', 4.0, 'standing height', 'Gollum', 'popculture', 9],
  ['harrypotter', '🧙', 'Harry Potter', 5.11, 'standing height', 'Harry Potter', 'popculture', 10],
  ['wednesday', '🖤', 'Wednesday Addams', 5.1, 'standing height', 'Wednesday Addams', 'popculture', 9],
  ['hermione', '🪄', 'Hermione Granger', 5.5, 'standing height', 'Hermione Granger', 'popculture', 9],
  ['batman', '🦇', 'Batman', 6.2, 'standing height', 'Batman', 'popculture', 10],
  ['superman', '🦸', 'Superman', 6.3, 'standing height', 'Superman', 'popculture', 10],
  ['wonderwoman', '🦸‍♀️', 'Wonder Woman', 6.0, 'standing height', 'Wonder Woman', 'popculture', 9],
  ['jacksparrow', '🏴‍☠️', 'Captain Jack Sparrow', 5.10, 'standing height', 'Jack Sparrow', 'popculture', 9],
  ['kingkong', '🦍', 'King Kong', 25.0, 'standing height', 'King Kong', 'popculture', 9],
  ['godzilla', '🦖', 'Godzilla', 393.0, 'standing height in the modern film version', 'Godzilla', 'popculture', 10],
  ['groot', '🌳', 'Groot', 23.0, 'adult standing height', 'Groot', 'popculture', 9],
  ['barbie', '👱‍♀️', 'Barbie', 0.96, 'doll height, about 11.5 inches', 'Barbie', 'popculture', 10],
  ['sherlock', '🔎', 'Sherlock Holmes', 6.0, 'standing height', 'Sherlock Holmes', 'popculture', 9],
  ['dracula', '🧛', 'Dracula', 6.2, 'standing height', 'Dracula', 'popculture', 9],
  ['frankenstein', '🧟', 'Frankenstein', 8.0, 'standing height', 'Frankenstein', 'popculture', 9],
  ['dorothy', '👠', 'Dorothy', 4.5, 'standing height', 'Dorothy', 'popculture', 9],
  ['santa', '🎅', 'Santa Claus', 6.0, 'estimated standing height', 'Santa Claus', 'popculture', 10],
  // animals
  ['giraffe', '🦒', 'a giraffe', 18.0, 'adult male standing height, ground to the top of its ossicones', 'Giraffe', 'animals', 10],
  ['ostrich', null, 'an ostrich', 9.0, 'adult male standing height', 'Ostrich', 'animals', 9],
  ['elephant', '🐘', 'an African elephant', 12.0, 'adult bull, ground to the top of its head and ears', 'African Elephant', 'animals', 10],
  ['moose', null, 'a moose', 8.0, 'adult bull, ground to the top of its antlers', 'Moose', 'animals', 8],
  ['horse', '🐎', 'a horse', 6.75, 'standing, ground to the top of its ears', 'Horse', 'animals', 10],
  ['camel', '🐪', 'a camel', 7.5, 'standing, ground to the top of its ears', 'Camel', 'animals', 9],
  ['bison', '🦬', 'an American bison', 6.3, 'adult bull, ground to the top of its horns', 'American Bison', 'animals', 8],
  ['gorilla', '🦍', 'a gorilla', 5.5, 'silverback standing upright', 'Gorilla', 'animals', 9],
  ['polarbear', null, 'a polar bear', 10.0, 'adult male standing on its hind legs, ground to the top of its ears', 'Polar Bear', 'animals', 9],
  ['grizzly', null, 'a grizzly bear', 8.5, 'adult male standing on its hind legs, ground to the top of its ears', 'Grizzly Bear', 'animals', 8],
  ['kangaroo', '🦘', 'a red kangaroo', 6.0, 'adult male standing tall', 'Red Kangaroo', 'animals', 8],
  ['penguin', '🐧', 'an emperor penguin', 4.0, 'adult standing height', 'Emperor Penguin', 'animals', 8],
  ['lion', null, 'a lion', 5.25, 'adult male, ground to the top of its mane', 'Lion', 'animals', 10],
  ['tiger', '🐅', 'a tiger', 4.25, 'standing, ground to the top of its ears', 'Tiger', 'animals', 9],
  ['greatdane', null, 'a Great Dane', 3.7, 'male, standing, ground to the top of its ears', 'Great Dane', 'animals', 7],
  ['flamingo', '🦩', 'a flamingo', 4.5, 'standing height', 'Flamingo', 'animals', 8],
  // vehicles
  ['car', '🚗', 'a sedan', 4.8, 'overall vehicle height', 'Sedan', 'vehicles', 10],
  ['suv', '🚙', 'an SUV', 6.2, 'overall vehicle height', 'SUV', 'vehicles', 10],
  ['pickup', '🛻', 'a pickup truck', 6.4, 'overall vehicle height', 'Pickup Truck', 'vehicles', 10],
  ['bus', 'art:schoolbus', 'a school bus', 10.5, 'overall vehicle height', 'School Bus', 'vehicles', 10],
  ['semitruck', '🚛', 'a semi truck', 13.5, 'overall height with the trailer', 'Semi Truck', 'vehicles', 9],
  ['routemaster', null, 'a double-decker bus', 14.4, 'overall vehicle height', 'Double-Decker Bus', 'vehicles', 9],
  ['monstertruck', null, 'a monster truck', 12.0, 'overall vehicle height', 'Monster Truck', 'vehicles', 8],
  ['ambulance', '🚑', 'an ambulance', 9.0, 'overall height, lights included', 'Ambulance', 'vehicles', 9],
  ['firetruck', '🚒', 'a fire truck', 10.5, 'overall vehicle height', 'Fire Truck', 'vehicles', 9],
  // landmarks
  ['liberty', 'art:libertyfull', 'the Statue of Liberty', 305, 'ground to torch, including the pedestal', 'Statue of Liberty', 'landmarks', 10],
  ['bigben', null, 'Big Ben', 316, 'the Elizabeth Tower, to the top of its spire', 'Big Ben', 'landmarks', 10],
  ['spaceneedle', null, 'the Space Needle', 605, 'total height', 'Space Needle', 'landmarks', 9],
  ['arch', null, 'the Gateway Arch', 630, 'total height', 'Gateway Arch', 'landmarks', 8],
  ['goldengate', null, 'a Golden Gate Bridge tower', 746, 'tower height above the water', 'Golden Gate Tower', 'landmarks', 9],
  ['eiffel', null, 'the Eiffel Tower', 1083, 'total height, antennas included', 'Eiffel Tower', 'landmarks', 10],
  ['empire', null, 'the Empire State Building', 1454, 'ground to the top of its antenna', 'Empire State Building', 'landmarks', 10],
  ['onewtc', null, 'One World Trade Center', 1776, 'architectural height, spire included', 'One World Trade Center', 'landmarks', 9],
  ['burj', null, 'the Burj Khalifa', 2717, 'architectural height', 'Burj Khalifa', 'landmarks', 9],
  ['washington', null, 'the Washington Monument', 555, 'total height', 'Washington Monument', 'landmarks', 9],
  ['christ', null, 'Christ the Redeemer', 125, 'statue and pedestal', 'Christ the Redeemer', 'landmarks', 9],
  // structures and rides
  ['ferriswheel', '🎡', 'a Ferris wheel', 150, 'a typical big fairground wheel', 'Ferris Wheel', 'rides', 9],
  ['londoneye', '🎡', 'the London Eye', 443, 'total height', 'London Eye', 'rides', 8],
  ['kingdaka', 'art:topthrill', 'the Kingda Ka roller coaster', 456, 'top of the tower (the ride ran 2005-2024)', 'Kingda Ka', 'rides', 7],
  ['fury325', null, 'the Fury 325 roller coaster', 335, 'ground to the top of the decorative marker above the lift hill (approximate)', 'Fury 325', 'rides', 6],
  ['celltower', null, 'a cell tower', 150, 'a typical lattice tower', 'Cell Tower', 'rides', 8],
  ['watertower', null, 'a water tower', 130, 'a typical town water tower', 'Water Tower', 'rides', 8],
  // prehistoric
  ['trex', '🦖', 'a T. rex', 12, 'standing height, to the top of its head', 'T. rex', 'dinos', 10],
  ['raptor', '🦖', 'a Velociraptor', 3, 'standing height, to the top of its head', 'Velociraptor', 'dinos', 8],
  ['triceratops', null, 'a Triceratops', 12, 'standing, ground to the top of its horns', 'Triceratops', 'dinos', 9],
  ['stegosaurus', null, 'a Stegosaurus', 14, 'to the top of its back plates', 'Stegosaurus', 'dinos', 9],
  ],
    NOT_UPRIGHT: [],
    ANCHORS: ['person', 'door', 'car', 'bus', 'house', 'liberty', 'phone', 'hoop', 'eiffel', 'giraffe', 'elephant', 'bigben']
  };
})();
