window.NN_DATA = {
  countries: [
    "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan",
    "Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi",
    "Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Republic of the Congo)","Costa Rica","Côte d'Ivoire","Croatia","Cuba","Cyprus","Czechia",
    "Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia",
    "Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana",
    "Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy",
    "Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
    "Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar",
    "Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway",
    "Oman","Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
    "Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria",
    "Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu",
    "Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
  ],
  answerAliases: {
    "america":"United States","usa":"United States","u s a":"United States","us":"United States","u s":"United States","united states of america":"United States",
    "uk":"United Kingdom","u k":"United Kingdom","great britain":"United Kingdom","britain":"United Kingdom",
    "czech republic":"Czechia","burma":"Myanmar","cape verde":"Cabo Verde","ivory coast":"Côte d'Ivoire","swaziland":"Eswatini",
    "east timor":"Timor-Leste","turkiye":"Turkey","türkiye":"Turkey","vatican":"Vatican City","south korea":"South Korea","republic of korea":"South Korea",
    "north korea":"North Korea","dprk":"North Korea","lao pdr":"Laos"
  },
  geometryAliases: {
    "United States":["United States of America"],
    "Bosnia and Herzegovina":["Bosnia and Herz.","Bosnia and Herzegovina"],
    "Central African Republic":["Central African Rep.","Central African Republic"],
    "Congo (Republic of the Congo)":["Congo"],
    "Côte d'Ivoire":["Côte d'Ivoire","Ivory Coast"],
    "Dominican Republic":["Dominican Rep.","Dominican Republic"],
    "Equatorial Guinea":["Eq. Guinea","Equatorial Guinea"],
    "Eswatini":["eSwatini","Eswatini"],
    "North Macedonia":["North Macedonia","Macedonia"],
    "South Sudan":["S. Sudan","South Sudan"],
    "Vatican City":["Vatican"]
  },
  routes: [
    ["France","Paris",2.3522,48.8566,1,["Spain","Belgium","Germany","Switzerland","Italy"]],
    ["Germany","Berlin",13.4050,52.5200,1,["Denmark","Poland","Czechia","Austria","Switzerland","France","Belgium","Netherlands"]],
    ["Spain","Madrid",-3.7038,40.4168,1,["Portugal","France"]],
    ["Portugal","Lisbon",-9.1393,38.7223,1,["Spain"]],
    ["Italy","Rome",12.4964,41.9028,1,["France","Switzerland","Austria","Slovenia"]],
    ["Belgium","Brussels",4.3517,50.8503,1,["France","Germany","Netherlands"]],
    ["Netherlands","Amsterdam",4.9041,52.3676,1,["Belgium","Germany"]],
    ["Switzerland","Bern",7.4474,46.9480,1,["France","Germany","Austria","Italy"]],
    ["Austria","Vienna",16.3738,48.2082,1,["Germany","Czechia","Slovakia","Hungary","Slovenia","Italy","Switzerland"]],
    ["Poland","Warsaw",21.0122,52.2297,1,["Germany","Czechia","Slovakia","Ukraine","Belarus","Lithuania"]],
    ["Denmark","Copenhagen",12.5683,55.6761,1,["Germany"]],
    ["Norway","Oslo",10.7522,59.9139,1,["Sweden","Finland"]],
    ["Sweden","Stockholm",18.0686,59.3293,1,["Norway","Finland"]],
    ["Finland","Helsinki",24.9384,60.1699,1,["Sweden","Norway","Russia"]],
    ["Czechia","Prague",14.4378,50.0755,1,["Germany","Poland","Slovakia","Austria"]],
    ["Greece","Athens",23.7275,37.9838,1,["Albania","Bulgaria","Turkey"]],
    ["Turkey","Ankara",32.8597,39.9334,1,["Greece","Bulgaria","Georgia","Armenia","Iran","Iraq","Syria"]],
    ["Egypt","Cairo",31.2357,30.0444,1,["Libya","Sudan","Israel"]],
    ["Morocco","Rabat",-6.8498,34.0209,1,["Algeria"]],
    ["South Africa","Pretoria",28.2293,-25.7479,1,["Namibia","Botswana","Zimbabwe","Mozambique"]],
    ["Argentina","Buenos Aires",-58.3816,-34.6037,1,["Chile","Bolivia","Paraguay","Brazil","Uruguay"]],
    ["Chile","Santiago",-70.6693,-33.4489,1,["Peru","Bolivia","Argentina"]],
    ["Brazil","Brasília",-47.8825,-15.7942,1,["Uruguay","Argentina","Paraguay","Bolivia","Peru","Colombia","Venezuela","Guyana","Suriname"]],
    ["Peru","Lima",-77.0428,-12.0464,1,["Ecuador","Colombia","Brazil","Bolivia","Chile"]],
    ["Mexico","Mexico City",-99.1332,19.4326,1,["United States","Guatemala","Belize"]],
    ["Canada","Ottawa",-75.6972,45.4215,1,["United States"]],
    ["United States","Washington, D.C.",-77.0369,38.9072,1,["Canada","Mexico"]],
    ["India","New Delhi",77.2090,28.6139,1,["Pakistan","China","Nepal","Bhutan","Bangladesh","Myanmar"]],
    ["China","Beijing",116.4074,39.9042,1,["Mongolia","Russia","Kazakhstan","Pakistan","India","Nepal","Bhutan","Myanmar","Laos","Vietnam","North Korea"]],
    ["South Korea","Seoul",126.9780,37.5665,1,["North Korea"]],

    ["Estonia","Tallinn",24.7536,59.4370,2,["Latvia","Russia"]],
    ["Latvia","Riga",24.1052,56.9496,2,["Estonia","Lithuania","Russia","Belarus"]],
    ["Lithuania","Vilnius",25.2797,54.6872,2,["Latvia","Belarus","Poland"]],
    ["Slovakia","Bratislava",17.1077,48.1486,2,["Czechia","Poland","Ukraine","Hungary","Austria"]],
    ["Hungary","Budapest",19.0402,47.4979,2,["Austria","Slovakia","Ukraine","Romania","Serbia","Croatia","Slovenia"]],
    ["Romania","Bucharest",26.1025,44.4268,2,["Hungary","Serbia","Bulgaria","Ukraine"]],
    ["Bulgaria","Sofia",23.3219,42.6977,2,["Romania","Serbia","Greece","Turkey"]],
    ["Croatia","Zagreb",15.9819,45.8150,2,["Slovenia","Hungary","Serbia"]],
    ["Serbia","Belgrade",20.4489,44.7866,2,["Hungary","Romania","Bulgaria","Croatia"]],
    ["Georgia","Tbilisi",44.7930,41.7151,2,["Russia","Turkey","Armenia","Azerbaijan"]],
    ["Armenia","Yerevan",44.5152,40.1872,2,["Georgia","Azerbaijan","Iran","Turkey"]],
    ["Iran","Tehran",51.3890,35.6892,2,["Turkey","Armenia","Azerbaijan","Turkmenistan","Afghanistan","Pakistan","Iraq"]],
    ["Iraq","Baghdad",44.3661,33.3152,2,["Turkey","Iran","Saudi Arabia","Jordan","Syria"]],
    ["Jordan","Amman",35.9106,31.9539,2,["Iraq","Saudi Arabia","Israel","Syria"]],
    ["Algeria","Algiers",3.0588,36.7538,2,["Morocco","Tunisia","Libya","Niger","Mali"]],
    ["Tunisia","Tunis",10.1815,36.8065,2,["Algeria","Libya"]],
    ["Libya","Tripoli",13.1913,32.8872,2,["Tunisia","Algeria","Niger","Chad","Sudan","Egypt"]],
    ["Kenya","Nairobi",36.8219,-1.2921,2,["Ethiopia","Somalia","Uganda","Tanzania"]],
    ["Tanzania","Dodoma",35.7516,-6.1630,2,["Kenya","Uganda","Rwanda","Burundi","Zambia","Malawi","Mozambique"]],
    ["Namibia","Windhoek",17.0832,-22.5609,2,["Angola","Zambia","Botswana","South Africa"]],
    ["Botswana","Gaborone",25.9231,-24.6282,2,["Namibia","Zambia","Zimbabwe","South Africa"]],
    ["Bolivia","La Paz",-68.1193,-16.4897,2,["Peru","Brazil","Paraguay","Argentina","Chile"]],
    ["Paraguay","Asunción",-57.5759,-25.2637,2,["Bolivia","Brazil","Argentina"]],
    ["Uruguay","Montevideo",-56.1645,-34.9011,2,["Brazil","Argentina"]],
    ["Colombia","Bogotá",-74.0721,4.7110,2,["Panama","Venezuela","Brazil","Peru","Ecuador"]],
    ["Venezuela","Caracas",-66.9036,10.4806,2,["Colombia","Brazil","Guyana"]],
    ["Ecuador","Quito",-78.4678,-0.1807,2,["Colombia","Peru"]],
    ["Guatemala","Guatemala City",-90.5069,14.6349,2,["Mexico","Belize","Honduras","El Salvador"]],
    ["Costa Rica","San José",-84.0907,9.9281,2,["Nicaragua","Panama"]],
    ["Panama","Panama City",-79.5199,8.9824,2,["Costa Rica","Colombia"]],
    ["Mongolia","Ulaanbaatar",106.9057,47.8864,2,["Russia","China"]],
    ["Kazakhstan","Astana",71.4704,51.1694,2,["Russia","China","Kyrgyzstan","Uzbekistan","Turkmenistan"]],
    ["Pakistan","Islamabad",73.0479,33.6844,2,["Iran","Afghanistan","China","India"]],
    ["Nepal","Kathmandu",85.3240,27.7172,2,["China","India"]],
    ["Thailand","Bangkok",100.5018,13.7563,2,["Myanmar","Laos","Cambodia","Malaysia"]],
    ["Vietnam","Hanoi",105.8342,21.0278,2,["China","Laos","Cambodia"]],
    ["Cambodia","Phnom Penh",104.9282,11.5564,2,["Thailand","Laos","Vietnam"]],

    ["Ukraine","Kyiv",30.5234,50.4501,3,["Poland","Slovakia","Hungary","Romania","Belarus","Russia"]],
    ["Belarus","Minsk",27.5615,53.9045,3,["Latvia","Lithuania","Poland","Ukraine","Russia"]],
    ["Slovenia","Ljubljana",14.5058,46.0569,3,["Italy","Austria","Hungary","Croatia"]],
    ["Albania","Tirana",19.8187,41.3275,3,["Greece"]],
    ["Saudi Arabia","Riyadh",46.6753,24.7136,3,["Jordan","Iraq","Kuwait","Qatar","United Arab Emirates","Oman","Yemen"]],
    ["Ethiopia","Addis Ababa",38.7578,8.9806,3,["Sudan","South Sudan","Kenya","Somalia","Djibouti","Eritrea"]],
    ["Zambia","Lusaka",28.3228,-15.3875,3,["Angola","Namibia","Botswana","Zimbabwe","Mozambique","Malawi","Tanzania"]],
    ["Zimbabwe","Harare",31.0522,-17.8252,3,["Zambia","Mozambique","South Africa","Botswana"]],
    ["Mozambique","Maputo",32.5732,-25.9692,3,["South Africa","Zimbabwe","Zambia","Malawi","Tanzania"]],
    ["Angola","Luanda",13.2344,-8.8383,3,["Namibia","Zambia"]],
    ["Nicaragua","Managua",-86.2514,12.1150,3,["Honduras","Costa Rica"]],
    ["Honduras","Tegucigalpa",-87.2068,14.0723,3,["Guatemala","El Salvador","Nicaragua"]],
    ["El Salvador","San Salvador",-89.2182,13.6929,3,["Guatemala","Honduras"]],
    ["Belize","Belmopan",-88.7669,17.2510,3,["Mexico","Guatemala"]],
    ["Myanmar","Naypyidaw",96.0785,19.7633,3,["India","Bangladesh","China","Laos","Thailand"]],
    ["Laos","Vientiane",102.6331,17.9757,3,["China","Myanmar","Thailand","Cambodia","Vietnam"]],
    ["Bangladesh","Dhaka",90.4125,23.8103,3,["India","Myanmar"]],
    ["Afghanistan","Kabul",69.2075,34.5553,3,["Iran","Turkmenistan","Uzbekistan","Tajikistan","China","Pakistan"]],
    ["Uzbekistan","Tashkent",69.2401,41.2995,3,["Kazakhstan","Kyrgyzstan","Tajikistan","Afghanistan","Turkmenistan"]],
    ["Turkmenistan","Ashgabat",58.3261,37.9601,3,["Kazakhstan","Uzbekistan","Afghanistan","Iran"]],
    ["Kyrgyzstan","Bishkek",74.5698,42.8746,3,["Kazakhstan","Uzbekistan","Tajikistan","China"]],
    ["Tajikistan","Dushanbe",68.7870,38.5598,3,["Kyrgyzstan","Uzbekistan","Afghanistan","China"]]
  ]
};
